name: 发布脚本

on:
  #监听 tags 操作
  push:
    tags:
      - 'v*' # 推送 v 开头的 tag 触发该脚本

jobs:
  build-and-deploy:
    # 构建环境使用 ubuntu 指定版本
    runs-on: ubuntu-22.04
    # 步骤
    steps:
      - name: 1.拉取代码
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: 2.安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.0'

      - name: 3.发布到 npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # npm access tokens
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm publish --access public
